# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57690cfe3cb70be4881561d029017bf231af559e512d9eece5386dd0bb1c5581022234c15f648a1422dc810df8fac113a46c15bc4fa69ee8a4178909dba61381

test:
  secret_key_base: 49c6ef27a250958d9431cf7bb5240fa3bf19cc09c470040872f1c3051471d370e599bf5fb62a3f5f0765e436d46a975d1c8de6dd827fa82cc1d849021aed4629

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
